# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f81vJ_qkWwr5CCVzHxz-9sk7RAK8pnhs
"""

# ! pip install shap

import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier as RF

data = pd.read_csv('https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv')
data = data.drop('DateTime',axis=1)
data = data.drop('id',axis=1)

test_data = pd.read_csv('https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv')
test_data = test_data.drop('DateTime',axis=1)
test_data = test_data.drop('id',axis=1)

y = data['meal']
x = data.drop('meal', axis=1)

#yt = test_data['meal']
xt = test_data.drop('meal', axis=1)

model = RF(n_estimators=100, n_jobs=-1, max_depth=50)
modelFit = model.fit(x, y)

pred = model.predict(xt)